spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 12121212

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  security:
    user:
      name: th
      password: 1

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.loginStudy.domain # result type에 패키지명을 생략할 수 있도록 alias 설정

